ALTER TABLE TB_INDEX ADD COLUMN month INTEGER NULL;
ALTER TABLE TB_INDEX ADD COLUMN i_num_m_3 NUMERIC NULL;
ALTER TABLE TB_INDEX ADD COLUMN i_num_m_2 NUMERIC NULL;
ALTER TABLE TB_INDEX ADD COLUMN i_num_m_1 NUMERIC NULL;
ALTER TABLE TB_INDEX ADD COLUMN i_num_med NUMERIC NULL;
ALTER TABLE TB_INDEX ADD COLUMN i_num_p_1 NUMERIC NULL;
ALTER TABLE TB_INDEX ADD COLUMN i_num_p_2 NUMERIC NULL;
ALTER TABLE TB_INDEX ADD COLUMN i_num_p_3 NUMERIC NULL;